export const CHANGE_PROJECT_FIELD = 'CHANGE_PROJECT_FIELD';

export const CHANGE_LANGUAGE_FIELD = 'CHANGE_LANGUAGE_FIELD';

export const REQUEST_PROJECTS_PENDING = 'REQUEST_PROJECTS_PENDING';

export const REQUEST_PROJECTS_SUCCESS = 'REQUEST_PROJECTS_SUCCESS';

export const REQUEST_PROJECTS_FAILED = 'REQUEST_PROJECTS_FAILED';

export const REQUEST_PROJECTS_SUCCESS_NEXT = 'REQUEST_PROJECTS_SUCCESS_NEXT';

export const REQUEST_PROJECTS_SUCCESS_PREV = 'REQUEST_PROJECTS_SUCCESS_PREV'